build_from:
  aarch64: "ghcr.io/analogj/scrutiny:master-collector"
  amd64: "ghcr.io/analogj/scrutiny:master-collector"
  armv7: "ghcr.io/analogj/scrutiny:master-collector"
  i386: "ghcr.io/analogj/scrutiny:master-collector"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Scrutiny Disk Monitor Backend"
  org.opencontainers.image.description: "Scrutiny Disk Monitor Backend for HASS Addon."
  org.opencontainers.image.source: "https://github.com/AnalogJ/scrutiny"
  org.opencontainers.image.licenses: "Apache License 2.0"