name: "Scrutiny Disk Monitor Backend - HASS Add On"
description: >-
  "Scrutiny Disk Monitor Backend forked from AnalogJ"
version: "master-collector"
init: false
slug: "scrutiny"
panel_icon: mdi:glasses
ingress: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: services
hassio_role: admin
full_access: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - DAC_READ_SEARCH
apparmor: true
environment:
  COLLECTOR_API_ENDPOINT: "http://192.168.1.126:8083"
  COLLECTOR_CRON_SCHEDULE: "*/10 * * * *"
  COLLECTOR_HOST_ID: "jollylife_ha"
host_pid: true
docker_api: true
udev: true
journald: true
map:
  - config:rw
image: "ghcr.io/analogj/scrutiny"