name: "Scrutiny Disk Monitor Backend - HASS Add On"
description: >-
  "Scrutiny Disk Monitor Backend forked from AnalogJ"
version: "master-collector"
init: false
slug: "scrutiny"
panel_icon: mdi:docker
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: services
hassio_role: admin
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
  - DAC_READ_SEARCH
apparmor: false
environment:
  COLLECTOR_API_ENDPOINT: "http://192.168.1.126:8083"
  COLLECTOR_CRON_SCHEDULE: "*/10 * * * *"
  COLLECTOR_HOST_ID: "jollylife_ha"
  PUID: 0
  PGID: 0
host_pid: true
docker_api: true
udev: true
journald: true
devices:
  - /dev/sda
map:
  - config:rw
image: "ghcr.io/analogj/scrutiny"