name: "Docker Socket Proxy - HASS Add On"
description: >-
  "Docker socket proxy forked from Tecnativa"
version: "0.1.2"
init: false
slug: "socketproxy"
panel_icon: mdi:docker
ports:
  2375/tcp: 2376
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: services
full_access: true
apparmor: false
environment:
  ALLOW_RESTARTS: "0"
  ALLOW_START: "0"
  ALLOW_STOP: "0"
  AUTH: "0"
  BUILD: "0"
  COMMIT: "0"
  CONFIGS: "0"
  CONTAINERS: "1"
  DISABLE_IPV6: "0"
  DISTRIBUTION: "0"
  EVENTS: "1"
  EXEC: "0"
  GRPC: "0"
  IMAGES: "0"
  INFO: "1"
  LOG_LEVEL: "info"
  PING: "1"
  PLUGINS: "0"
  POST: "0"
  VERSION: "1"
  SYSTEM: "1"
host_pid: true
docker_api: true
image: "tecnativa/docker-socket-proxy"